### ISSUE TITLE
Test suite fails to build

### ISSUE THREAD

**Issue by mdorman** [feuerbach/regex-applicative#24]
When trying to build 0.3.2 on nixos, the test suite errors out because it can't find the 'StateQueue' module.  Looks like a typo, and it should be Text.Regex.Applicative.StateQueue, no?

http://hydra.cryp.to/build/949856/nixlog/2/raw has details.

**Comment by feuerbach** [comment]
No, it's a different module that wasn't listed in the cabal file and so didn't make it to the tarball. Should be fixed in 0.3.2.1. Thanks for the notice.
