### ISSUE TITLE
Debuggin function RE -> String

### ISSUE THREAD

**Issue by nomeata** [feuerbach/regex-applicative#28]
After creating some rather complex regular expression assembly DSL, in the end I get a pattern match failure, and now I am having a hard time to debug my code. It would be great if `RE` had a show instance, or maybe some `debugShow :: Show s => RE s a -> String` function that explains the structure of the regular expression.

**Comment by ocharles** [comment]
I'd love to have this too, but I don't think it's feasible. The fundamental matching primitive in `RE` is:

```haskell
    Symbol :: ThreadId -> (s -> Maybe a) -> RE s a
```

That is, a function mapping tokens to some parsed variation. Thus there's no way to know what the regular expression expects to be able to proceed.

**Comment by feuerbach** [comment]
Related: #36

**Comment by feuerbach** [comment]
In fact, I think I'm going to close this one in favour of #36, as it is a bit more constructive.
