### ISSUE TITLE
0.3.3 and docs on hackage

### ISSUE THREAD

**Issue by alogic0** [feuerbach/regex-applicative#29]
There is no docs on Hackage for latest version.
https://hackage.haskell.org/package/regex-applicative

The Stackage has one
https://www.stackage.org/nightly-2016-01-02/package/regex-applicative-0.3.3

**Comment by feuerbach** [comment]
Ok, is there anything you want me to do here?

**Comment by alogic0** [comment]
No. Don't know where is the best place to write about such bugs.

**Comment by alogic0** [comment]
However, in your [README](https://github.com/feuerbach/regex-applicative/blob/master/README.md) link  `API reference` points to the Hackage page. So now it is broken.

**Comment by feuerbach** [comment]
Well, at least it says where to go.

I can't link to stackage because there's no way to link to the latest version that I know of.
