### ISSUE TITLE
Convert regex to another parser?

### ISSUE THREAD

**Issue by Zemyla** [feuerbach/regex-applicative#31]
I am wondering if it would be possible to convert a `Re` to another parser type, with a signature something like:

``` haskell
toParser :: (Alternative f) => (forall t. (s -> Maybe t) -> f t) -> RE s a -> f a
```

This way, we could build a regular expression, then use it in another parser such as Parsec, and still get the favorable linear no-backtracking behavior. The general type signature enables you to do this without incurring a dependency on any parser package.

Also, it can be tested with the P monad in Reference, and it should give the same results as `reference`.

**Comment by feuerbach** [comment]
This can be done, yes. (Not sure about that specific signature.) I think the object interface should suffice to implement this.
