### ISSUE TITLE
Haddocks for RE don't show typeclass instances

### ISSUE THREAD

**Issue by seagreen** [feuerbach/regex-applicative#35]
[Here are the current Haddocks](http://hackage.haskell.org/package/regex-applicative-0.3.3/docs/Text-Regex-Applicative.html#t:RE). The comment mentions that `RE` is a `Functor`, `Applicative`, and `Alternative`, but the normal Haddock instance descriptions don't show up.

I'm guessing that has to do with them being [declared as orphans](
https://github.com/feuerbach/regex-applicative/blob/2205b008fc41f60060cec91bcf1a3907ed7b600a/Text/Regex/Applicative/Interface.hs#L13). Could this be fixed by moving those orphan instances alongside the definition of `RE`? If so I'd be happy to make a PR for it.

**Comment by feuerbach** [comment]
Nah, it's just that the last release was made in 2015, when haddock didn't know to display instances. I've uploaded a dummy minor release (0.3.3.1), so that's fixed now.
