### ISSUE TITLE
Semigroup instance?

### ISSUE THREAD

**Issue by chrisdone** [feuerbach/regex-applicative#37]
I've found with the -text variant of this package, when doing sophisticated replacements, it's neat to have a Semigroup instance and a helper `capture` function:
```haskell
capture = fmap snd . withMatched

instance Semigroup (RE' Text) where
  (<>) x y = (<>) <$> x <*> y
```

For example, I'm doing a script to rename modules, it looks like this:

```haskell
applyToContents config = replace inHeader
  where
    inHeader =
      capture (many (psym (\c -> elem c ['\n', '\r']))) <> string "module" <>
      capture (some (psym isSpace)) <>
      mname <>
      capture (some (psym isSpace))
    mname = string (configFrom config) *> pure (configTo config)
```

Without the `Semigroup`, I have to use `<*>` and `<$>` then `<>` to combine them.

Just throwing these out there. Using the returned value of the `Applicative` to do the replacement is totally awesome, by the way. Intuitive yet initially surprising.

**Comment by feuerbach** [comment]
Yeah, this makes sense to me. Perhaps also with a similarly lifted Monoid instance?

**Comment by chrisdone** [comment]
That seems intuitive and lawful! :thinking:

**Comment by feuerbach** [comment]
This is now in v0.3.4.
