### ISSUE TITLE
Recursive parsers

### ISSUE THREAD

**Issue by MostFrumiousBandersnatch** [feuerbach/regex-applicative#41]
Hi!
Sorry if i've chosen a wrong place, cause i have rather a question than an issue.

I  tried to construct a parser capable to [answer simple questions ](https://exercism.io/my/solutions/87c1dc2fd76b4c4d9b135c159299589d) like following:
- What is 7 minus 5?
- What is 5 plus 13 plus 6?

Even though such an expressions appears to be of one-level depth, i decided to make the parser recursive, since the target data type is recursive.

```
data Operation = Plus | Minus | Multiply | Divide deriving (Eq, Show)
data Expr = Plain Integer | Combined Expr Operation Expr deriving (Eq, Show)

parseExpr :: RE Char Expr
parseExpr = parseNum <|> Combined <$> parseNum <*> trim parseOp <*> parseExpr <|> R.empty

parseQuestion :: RE Char Expr
parseQuestion = R.string "What is " *> parseExpr <* R.string "?"
```
So, i've faced with problem. `parseExpr` works nicely with inputs like `"1"`, `"1 plus 2"`, `"1 plus 2 plus 3"` (actually, with all i tried), meanwhile `parseQuestion` fails due to non-terminated computations on correspondent inputs: `"What is 1?"`, `"What is 1 plus 2?"` etc.
That's because of trailing `"?"` for sure.

What i'd like to understand here is whether recursive parsing is somehow beyond the capabilities of applicative parser or i just did something wrong?

**Comment by feuerbach** [comment]
Yes, infinite regular expressions are explicitly not supported.

One way to look at it is, once you allow infinite regular expressions, the language they describe is no longer regular. E.g. you can easily recognize [well-formed parentheses](https://en.wikipedia.org/wiki/Context-free_grammar#Well-formed_parentheses) with an infinite/recursive regular expression.

Why do they work with parseExpr? You can look at this as a coincidence, or you can dig deeper and try to understand what properties of parseExpr make it work, but in any case I wouldn't rely on it.

**Comment by MostFrumiousBandersnatch** [comment]
Well, `parseExpr` didn't work till i terminated it with `R.empty`. I have to admit, that i did it without thorough understanding , i wanted to give it a try, but it worked.
Can't say anything for sure, besides that it works even being prefixed in a way like `R.string "What is " *> parseExpr`, but stops working in opposite case `parseExpr <* R.string "?"`.

**Comment by MostFrumiousBandersnatch** [comment]
Anyway, i got your point and refused to declare a parser as a recursive one, cause it's just unnecessary for this task.
Thanks for the reference to regular language.
Also, thank for a nice library.

**Comment by feuerbach** [comment]
👍
