### ISSUE TITLE
Lookahead, word boundaries?

### ISSUE THREAD

**Issue by ulidtko** [feuerbach/regex-applicative#43]
Hi!

This is really a question: can this lib do 1-char look-ahead? I've inspected the API, searched several places, and still am puzzled.

For example, say I wish to match a keyword `let` returning a `KeywordLet` value: I write `KeywordLet <$ RE.string "let"` — but that'll also match `foo letter` incorrectly.

Asked another way, how to spell `quux\b` or `quux(?!\w)` in `regex-applicative` ?

**Comment by feuerbach** [comment]
Hi.

This is not supported by this package directly but can be built on top of it. See e.g. https://hackage.haskell.org/package/lexer-applicative.
